### ISSUE TITLE
May I have your attention please?

### ISSUE THREAD

**Issue by fmsouza** [bernardolins/cr7#4]
I have been trying to reach you out for a while, but looks like your phone is not working anymore.

If you didn't checked my WhatsApp messages, last December I have invited you to my wedding with Rosana which will happen next September 28th, and I would like to send you the invitation. As it feels like the only social network you give attention to as of now is Github, I decided to raise an issue to get your attention, hope it works 😄 

So if you see this message, please contact me on the same number as always. I hope I can see you there in September.

Cheers,
Fred

**Comment by faustofjunqueira** [comment]
@bernardolins gostaria tbm de marcar uma breja com voce. Quando teria data disponivel?

Tbm estou no mesmo numero de ssempre!

Cheers!

**Comment by bernardolins** [comment]
Wow, that was very unexpected 🤣🤣🤣🤣🤣🤣🤣🤣🤣 

Hi @fmsouza, nice to hear you are getting married!! Those are great news!! 

I am sorry, I don't use WhatsApp quite often, but we can chat on Facebook or by phone, the number is probably the same. But if it's better for you, I can open an issue on a project you own. 😄 

I hope to hear from you soon.
